INSERT INTO pid(id_pid,id_usuario,id_periodo) VALUES (20,286,15);
INSERT INTO pid(id_pid,id_usuario,id_periodo) VALUES (21,288,15);
INSERT INTO pid(id_pid,id_usuario,id_periodo) VALUES (22,290,15);
INSERT INTO pid(id_pid,id_usuario,id_periodo) VALUES (23,291,15);
INSERT INTO pid(id_pid,id_usuario,id_periodo) VALUES (24,293,15);
INSERT INTO pid(id_pid,id_usuario,id_periodo) VALUES (25,294,15);
INSERT INTO pid(id_pid,id_usuario,id_periodo) VALUES (26,287,15);
INSERT INTO pid(id_pid,id_usuario,id_periodo) VALUES (27,295,15);
INSERT INTO pid(id_pid,id_usuario,id_periodo) VALUES (28,297,15);
INSERT INTO historico_pid(id_pid,etapa,situacao,data_situacao) VALUES (20,"PID","APROVADO","2023-03-30 17:00:00");
INSERT INTO historico_pid(id_pid,etapa,situacao,data_situacao) VALUES (21,"PID","APROVADO","2023-03-30 17:00:00");
INSERT INTO historico_pid(id_pid,etapa,situacao,data_situacao) VALUES (22,"PID","APROVADO","2023-03-30 17:00:00");
INSERT INTO historico_pid(id_pid,etapa,situacao,data_situacao) VALUES (23,"PID","APROVADO","2023-03-30 17:00:00");
INSERT INTO historico_pid(id_pid,etapa,situacao,data_situacao) VALUES (24,"PID","APROVADO","2023-03-30 17:00:00");
INSERT INTO historico_pid(id_pid,etapa,situacao,data_situacao) VALUES (25,"PID","APROVADO","2023-03-30 17:00:00");
INSERT INTO historico_pid(id_pid,etapa,situacao,data_situacao) VALUES (26,"PID","APROVADO","2023-03-30 17:00:00");
INSERT INTO historico_pid(id_pid,etapa,situacao,data_situacao) VALUES (27,"PID","APROVADO","2023-03-30 17:00:00");
INSERT INTO historico_pid(id_pid,etapa,situacao,data_situacao) VALUES (28,"PID","APROVADO","2023-03-30 17:00:00");
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (20,1,"ADS - AAIFE - Ação de Extensão Aplicada a Computação I",3);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (20,1,"ADS - Redes de Computadores II",4);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (20,1,"Técnico em Informática - Introdução aos Sistemas Operacionais",3.33);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (20,2,"Preparação de conteúdo EAD - WordPress",1);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (20,2,"Preparação de conteúdo EAD - PHP e Orientação a Objetos",1);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (20,2,"Preparação de conteúdo EAD - JavaScript",1);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (20,2,"Preparação de conteúdo EAD - Linguagem de Marcação de Hipertexto - HTML",1);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (20,2,"Preparação de conteúdo EAD - Organização e Arquitetura de Computadores",0.5);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (20,2,"Preparação de conteúdo EAD - Ajax e jQuery",0.5);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (20,2,"Preparação de conteúdo EAD - Design Responsivo com Boostrap",0.5);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (20,2,"Preparação de conteúdo EAD - Folhas de Estilo em Cascata - CSS",1);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (20,3,"",5);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (20,4,"",5);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (20,5,"",5);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (20,6,"",1);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (20,7,"",0.43);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (20,8,"",0.2);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (20,9,"",0.2);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (20,68,"",6.34);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (21,1,"Ecologia dos Ecossistemas - TMA",1.66);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (21,1,"Agrofloresta - TMA",3.33);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (21,1,"Segurança do Trabalho - TGA",2);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (21,1,"TCC2 - TGA",2);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (21,1,"Certificação e comercialização de produtos orgânicos - FIC AO",2.5);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (21,2,"Elaboração de Estudos e Projetos Ambientais - FIC AFA",1);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (21,2,"Introdução ao Agronegócio - TA",3);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (21,3,"",3);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (21,4,"",2);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (21,5,"",1.51);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (21,6,"",1.5);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (21,7,"",3);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (21,8,"",1);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (21,9,"",1);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (21,22,"",2.1);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (21,23,"",1);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (21,24,"",0.1);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (21,25,"",0.2);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (21,26,"",0.1);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (21,69,"",8);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (22,1,"ALGORITMO E LÓGICA DE PROGRAMAÇÃO - ADS",4);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (22,1,"PROGRAMAÇÃO WEB II - ADS",4);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (22,1,"PROGRAMAÇÃO WEB I - TI",3.33);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (22,1,"PROGRAMAÇÃO WEB III - TI",3.33);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (22,3,"",4);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (22,4,"",4);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (22,5,"",3);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (22,6,"",0);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (22,7,"",3);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (22,8,"",0);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (22,9,"",0.7);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (22,19,"",2);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (22,69,"",7.8);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (22,75,"",0.8);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (23,1,"INF08017 - Banco de dado II ADS",4);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (23,1,"ADS08001 - Fundamentos da Computação",3);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (23,1,"INF08100 - ALGORITMOS E LÓGICA DE PROGRAMAÇÃO",3.35);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (23,1,"INF08114 - Banco de dado II Tec. Inf.",2.5);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (23,2,"AGRO08001 - AMBIENTAÇÃO EM EDUCAÇÃO À DISTÂNCIA",1);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (23,2,"AFA08001 - AMBIENTAÇÃO EM EAD",0.5);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (23,2,"PWEB08001 - AMBIENTAÇÃO EM EAD",0.5);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (23,2,"PWEB08002 - FUNDAMENTOS DE LÓGICA DE PROGRAMAÇÃO",1);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (23,2,"MRC08006 - MANUTENÇÃO PREVENTIVA E CORRETIVA DE COMPUTADORES",1.5);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (23,3,"",3);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (23,4,"",2);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (23,5,"",2);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (23,6,"",2);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (23,7,"",4);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (23,8,"",1);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (23,9,"",0.15);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (23,11,"",0.5);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (23,69,"",8);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (24,1,"Organização, Sistemas e Métodos (FIC ADM)",0.9);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (24,1,"Introdução à Gestão Ambiental (TGA)",1);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (24,1,"Matemática Financeira (ADS)",2);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (24,1,"Metodologia Científica II (ADS)",4);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (24,1,"Fundamentos da Administração (ADM)",3.33);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (24,1,"Gestão de Projetos (ADM)",1.67);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (24,1,"Gestão Ambiental (TMA)",0.83);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (24,2,"Gestão do Negócio e Empreendedorismo (AGN)",4);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (24,3,"",3.5);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (24,4,"",3.5);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (24,5,"",2);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (24,6,"",3);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (24,7,"",1.33);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (24,8,"",4);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (24,9,"",0.4);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (24,22,"",0.1);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (24,23,"",0.2);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (24,69,"",1.6);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (24,75,"",2.4);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (24,78,"",0.2);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (25,1,"Controle de Herbívoros, patógenos, plantas espontâneas (FIC)",2);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (25,2,"Educação Ambiental e Sanitária (FIC/preparação EAD)",1.5);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (25,2,"Noções de Avaliação de Impacto e Licenciamentos Ambiental (FIC/preparação EAD)",1);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (25,1,"Avaliação de Impacto e Licenciamento Ambiental (Graduação)",2);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (25,1,"Química Ambiental (Graduação)",2);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (25,1,"Educação Ambiental e Saúde",3.33);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (25,1,"Avaliação de Impacto e Licenciamento Ambiental (Técnico)",2.5);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (25,3,"",2);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (25,4,"",3);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (25,5,"",2);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (25,6,"",1);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (25,7,"",4);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (25,8,"",1.33);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (25,9,"",1);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (25,15,"",0.2);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (25,19,"",0.2);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (25,48,"",6.74);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (25,51,"",1);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (25,56,"",2);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (25,75,"",0.8);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (26,1,"Linguagem de Programação II - Técnico em Informática",3.33);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (26,1,"Introdução à Informática - Técnico em Agronegócio",2);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (26,1,"Linguagem de Programação II - Análise e Desenvolvimento de Sistemas",4);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (26,1,"Programação para dispositivos móveis - Análise e Desenvolvimento de Sistemas",4);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (26,2,"Ambientação da Educação a Distância - FIC Montador e Reparador de Computadores",0.5);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (26,2,"Instalação e Configuração de Sistemas Operacionais - FIC Montador e Reparador de Computadores",0.5);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (26,3,"",3);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (26,4,"",3);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (26,5,"",2);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (26,6,"",1);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (26,7,"",4);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (26,8,"",1);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (26,9,"",0.33);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (26,19,"",1.9);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (26,22,"",4);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (26,23,"",4);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (26,75,"",1);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (27,1,"AAIFE",2);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (27,1,"GESTÃO E TRATAMENTO DE RESÍDUOS SÓLIDOS- 3ºTGA",4);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (27,1,"ECOLOGIA BÁSICA-1ºTGA",2);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (27,1,"GESTÃO DE RESÍDUOS SÓLIDOS- 3ºTMA",4);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (27,2,"INTRODUÇÃO AO MANEJO DE RESÍDUOS SÓLIDOS-FIC (EAD)",1);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (27,2,"MANEJO E CONSERVAÇÃO DO SOLO E DA ÁGUA- TÉCNICO AGRONEGÓCIO (EAD)",2);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (27,3,"",3);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (27,4,"",3);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (27,5,"",3);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (27,6,"",2);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (27,7,"",2);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (27,8,"",1);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (27,9,"",1);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (27,10,"",4);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (27,49,"",2);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (27,69,"",4);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (28,1,"Fundamentos da Matemática ( Técnico em Administração)",3.33);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (28,2,"Fundamentos da Matemática (Agronegócio)",2);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (28,1,"Matemática Aplicada à Computação",4);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (28,1,"Matemática Aplicada ao Meio Ambiente",2.5);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (28,1,"Matemática Aplicada à Informática I",1.67);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (28,1,"Matemática Aplicada à Informática II",1.67);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (28,1,"Tópicos de Matemática",2);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (28,3,"",4.57);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (28,4,"",3);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (28,5,"",3);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (28,6,"",2);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (28,7,"",2);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (28,8,"",2);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (28,9,"",0.6);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (28,75,"",2.66);
INSERT INTO atividade_docente(id_pid,id_atividade,descricao,horas_planejadas) VALUE (28,81,"",3);
INSERT INTO historico_atividade (id_atividade_docente,etapa,situacao,observacao,data_situacao,id_usuario_avaliador) 
SELECT 
	id_atividade_docente,
	"PID",
	"APROVADA",
	"Importado da planilha, caso este item seja composto de várias atividades do mesmo tipo, o docente poderá juntar os comprovantes em um único PDF ou cadastrar um item para cada atividade.",
	"2023-03-30 17:00:00",
	285
FROM atividade_docente WHERE id_pid >= 20;