INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Língua Portuguesa e Literatura I",3,105,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Educação Física I",2,70,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Inglês I",1,35,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Física I",2,70,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Química I",2,70,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Biologia I",2,70,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Matemática I",3,105,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("História I",2,70,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Geografia I",2,70,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Arte I",1,35,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Fundamentos da Administração",2,70,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Administração de Marketing e Serviços",2,70,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Administração da Produção e Logística",2,70,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Informática básica",2,70,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Prática Pedagógica Integradora I",1,35,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Língua Portuguesa e Literatura II",3,105,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Redação I",1,35,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Educação Física II",2,70,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Inglês II",1,35,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Física II",2,70,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Química II",2,70,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Biologia II",2,70,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Matemática II",3,105,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("História II",1,35,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Geografia II",2,70,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Sociologia I",1,35,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Estratégia e Gestão I",2,70,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Empreendedorismo",2,70,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Recursos materiais e patrimoniais",2,70,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Matemática Financeira",2,70,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Prática Pedagógica Integradora II",1,35,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Língua Portuguesa e Literatura III",3,105,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Redação II",1,35,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Educação Física III",2,70,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Inglês III",1,35,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Física III",2,70,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Química III",2,70,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Biologia III",2,70,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Matemática III",3,105,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("História III",2,70,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Geografia III",1,35,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Filosofia I",1,35,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Prática Profissional Supervisionada",1,35,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Estratégia e Gestão II",2,70,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Gestão de Pessoas",3,105,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Administração Financeira",2,70,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Agronegócio",1,35,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Saúde e Segurança do Trabalho",1,35,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Planejamento de Carreira e Sucesso Profissional",1,35,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Mercado de capitais",1,35,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Economia de Mercado",1,35,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Economia Solidária",1,35,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Sistemas de Informações Gerenciais",1,35,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Tópicos Especiais em Administração",1,35,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Contabilidade Geral",1,35,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Administração de custos",1,35,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Inteligência Artificial Aplicada à Empresas e Negócios",1,35,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Redação técnica",1,35,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Inglês técnico",1,35,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Sociologia II",1,35,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Energia e sustentabilidade",1,35,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Libras",1,35,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Filosofia II",1,35,0);

INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Princípios de Ecologia e Conservação da Biodiversidade",2,70,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Agricultura e Meio Ambiente",2,70,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Educação Ambiental e Saúde",2,70,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Gestão de Recursos Hídricos",2,70,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Climatologia",2,70,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Projeto Integrador I",1,35,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Recuperação de Áreas Degradadas",2,70,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Gestão Ambiental ",2,70,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Química e Microbiologia Ambiental",2,70,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Solos",2,70,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Segurança do Trabalho",2,70,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Projeto Integrador II",1,35,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Gestão de Resíduos Sólidos",2,70,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Elaboração e Análise de Projetos Ambientais ",2,70,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Avaliação de Impactos e Licenciamento Ambiental",2,70,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Geotecnologias",2,70,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Optativa",1,35,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Projeto Integrador III",1,35,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Controle de poluição em processos Agroindustriais",1,35,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Tópicos em Legislação Ambiental",1,35,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Cafeicultura Ecológica",1,35,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Energia e Sustentabilidade",1,35,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Libras",1,35,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Evolução da Administração",1,35,0);
INSERT INTO disciplina (descricao,chs,cht,chs_ead) VALUES ("Planejamento de Carreira e Sucesso Profissional",1,35,0);